{% set version = "2.42-6" %}

package:
  name: r-survival
  version: {{ version.replace("-", "_") }}

source:
  fn: survival_{{ version }}.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/survival_{{ version }}.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/survival/survival_{{ version }}.tar.gz
  sha256: e33c44ee95961ff3c1bd1afe040d3059c143a72387d8e47fdbeba61c9d605daf

build:
  number: 0
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - posix  # [win]
    - m2w64-toolchain  # [win]
    - gcc  # [not win]
    - r-matrix
  run:
    - r-base
    - r-matrix

test:
  commands:
    - R -e "library('survival')"  # [not win]
    - R -e \"library('survival')\"  # [win]

about:
  home: https://github.com/therneau/survival
  license: LGPL-2.0
  summary: 'Contains the core survival analysis routines, including definition of Surv objects,  Kaplan-Meier
    and Aalen-Johansen (multi-state) curves, Cox models, and parametric accelerated
    failure time models.'

extra:
  recipe-maintainers:
    - ocefpaf
