{% set version = "2.42-4" %}

package:
  name: r-survival
  version: {{ version.replace("-", "_") }}

source:
  fn: survival_{{ version }}.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/survival_{{ version }}.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/survival/survival_{{ version }}.tar.gz
  sha256: 678266668ac956538ab18f9ec45509b501e090bacaa6f58e41fcaa8c4d36db3e

build:
  number: 0
  skip: True  # [win32]
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:  # [not win32]
  build:  # [not win32]
    - r-base  # [not win32]
    - posix  # [win64]
    - m2w64-toolchain  # [win64]
    - gcc  # [not win]
    - r-matrix  # [not win32]
  run:  # [not win32]
    - r-base  # [not win32]
    - r-matrix  # [not win32]

test:
  commands:
    - R -e "library('survival')"  # [not win]
    - R -e \"library('survival')\"  # [win]

about:
  home: https://github.com/therneau/survival
  license: LGPL-2.0
  summary: 'Contains the core survival analysis routines, including definition of Surv objects,  Kaplan-Meier
    and Aalen-Johansen (multi-state) curves, Cox models, and parametric accelerated
    failure time models.'

extra:
  recipe-maintainers:
    - ocefpaf
