appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: ci5QUeq8KvkNp+YtDgpLYo2r74UueF4/WqKMG3uwzk6yM1Q50vzZ2yTXzyrpxRzCpbTwFflk5nYMzju/Je6LQwGmvUe8hzNETutZcHl4syYXXyq+R6nWKiH5kIdssIKnVZRRkkgxpTbLBMxGVXHGd2BmaPPwU29n9lq8ZfrjHvuqynyPbrhSmACf/aov45JE1SuFywXV7llZ/09rRFBg7JnSk9mahFP5xlw31Cv/JDM7YdSYKyl49koUHpjhGNn7MlcT2gAsRX5h4/jOrD5O9AmvyZnB+GCVpoGRvEdnr8sZrFF1dFThDBK9Gymb+GDPfIR4BZhiXvuL2+NiLYXtMi2C5F0dQZCiYZ4zerJzCCC6IEHjjPNzaMlY5vjWQvW1rN2uA0AstbWvpuFofAllUScC3Yxk6gw05KugxetuiNgS/n6H3MrTWhJzXXJFP9KiC6YZNVUbdqtK7FXSZMqyLgWFVypJJ1bQoG98jRA0Y1OAiyKeU02/gJSkcBuAnS+0gOBg8KLuXDi/FNz6Im/B8Hv+ymHU4T/iTDJ5NaX8V4m1rBSYV8/ijstux2p9amfUT7LGW4Bsvv8X1nNajr4FU8QzWPjpeXQ+8HR6vx8/2Uae6clAvvsyoQBKrDZ3B36qOwemWJVEjEod6hhtL8L8ioS3uPXuZQ9i5BapVE+ggtU=}
bot:
  automerge: true
